### ISSUE TITLE
自定义控件中的组件如何接受 options

### ISSUE THREAD

**Issue by callcter** [Kchengz/k-form-design#10]
如题

**Comment by Kchengz** [comment]
> 如题

非常抱歉，这块文档没有完善，在下次提交，我完善一下文档自定义控件的文档，并提供自定义组件的示例代码

**Comment by Kchengz** [comment]
可以参考这个[demo](https://gitee.com/kcz66/k-form-design-demo),里面有自定义组件示例，及使用props方式接收options
