### ISSUE TITLE
switch类型默认值问题

### ISSUE THREAD

**Issue by Kerbores** [Kchengz/k-form-design#11]
switch类型的默认值不应该设置defaultValue而应该设置defaultChecked:详见[defaultChecked](https://www.antdv.com/components/switch-cn/#api)

**Comment by Kerbores** [comment]
上层业务代码处理的问题

**Comment by Kchengz** [comment]
> switch类型的默认值不应该设置defaultValue而应该设置defaultChecked：详见[defaultChecked](https://www.antdv.com/components/switch-cn/#api)

是的，只是json配置统一为了defaultValue，实际还是defaultChecked，代码如：
:defaultChecked="record.options.defaultValue"
[代码地址](https://github.com/Kchengz/k-form-design/blob/master/packages/KFormItem/index.vue#L175)175行
