### ISSUE TITLE
3.8.16版本添加动态表格组建后无法获取数据

### ISSUE THREAD

**Issue by L2421800049** [Kchengz/k-form-design#118]
添加动态表格组件后，在预览的界面无法获取数据。表单创建完成后点击 提交也无法触发getData的操作。回退到3.8.9就正常了。并且 还导致了部分的ant design 的组件css无效。

**Comment by Kchengz** [comment]
能否提供更具体的描述，截图或者提供报错的表单json结构，方便复现问题
在demo 页面http://cdn.kcz66.com/k-form-design.html，按你描述无法复现这个问题

**Comment by Kchengz** [comment]
https://github.com/Kchengz/k-form-design/issues/119
存在类似问题，已修复
