### ISSUE TITLE
建议增加左侧项可以自定义输出,

### ISSUE THREAD

**Issue by zhangfei8080** [Kchengz/k-form-design#12]

**Comment by Kchengz** [comment]
这个可以考虑在下一个版本添加自定义左侧菜单功能，用户可以选择输出自己需要的控件

**Comment by Kchengz** [comment]
> 这个可以考虑在下一个版本添加自定义左侧菜单功能，用户可以选择输出自己需要的控件

参考文档：[https://www.kcz66.com/k-form-design/#/zh-cn/components/design?id=api](https://www.kcz66.com/k-form-design/#/zh-cn/components/design?id=api)
