### ISSUE TITLE
加一个类似步骤表单的控件

### ISSUE THREAD

**Issue by vvschool** [Kchengz/k-form-design#120]
[加一个类似步骤表单的控件

**Comment by vvschool** [comment]
![微信截图_20230412143921](https://user-images.githubusercontent.com/54130219/231372881-30639d07-8aad-4dec-9941-d692a00341cb.png)

**Comment by Kchengz** [comment]
抱歉，由于作者精力有限，k-form-design 目前只会进行维护bug，不考虑组件扩展或者功能更新了
新功能都会优先开发 vue3版本的 [k-designer](https://gitee.com/kcz66/k-designer)

**Comment by Kchengz** [comment]
抱歉，由于作者精力有限，k-form-design 目前只会进行维护bug，不考虑组件扩展或者功能更新了
新功能都会优先开发 vue3版本的 [k-designer](https://gitee.com/kcz66/k-designer)
