### ISSUE TITLE
动态表单动态检验有bug

### ISSUE THREAD

**Issue by manongqiyin** [Kchengz/k-form-design#128]
我新建了一个模版，其中只有一个动态表单，表单元素有：TEXT、下拉选择，input。其中下拉选择和input是必填的，这两个组件都分别选择、填入信息了，不论如何都校验不通过。具体json如下：

{
	"list": [
		{
			"type": "batch",
			"label": "动态表格",
			"list": [
				{
					"type": "text",
					"label": "文字",
					"icon": "icon-zihao",
					"options": {
						"textAlign": "left",
						"showLabel": true,
						"hidden": false,
						"showRequiredMark": false,
						"noFormItem": true,
						"color": "rgba(0, 0, 0, 0.9)",
						"fontFamily": "",
						"fontSize": "10.5pt"
					},
					"key": "text_1708566987793"
				},
				{
					"type": "select",
					"label": "下拉选择器",
					"icon": "icon-xiala",
					"options": {
						"width": "100%",
						"multiple": false,
						"disabled": false,
						"clearable": false,
						"showLabel": true,
						"hidden": false,
						"placeholder": "请选择",
						"dynamicKey": "",
						"dynamic": false,
						"options": [
							{
								"value": "1",
								"label": "下拉框1"
							},
							{
								"value": "2",
								"label": "下拉框2"
							}
						],
						"showSearch": false
					},
					"model": "select_1708567002340",
					"key": "select_1708567002340",
					"help": "",
					"rules": [
						{
							"required": true,
							"message": "必填项"
						}
					]
				},
				{
					"type": "input",
					"label": "输入框",
					"icon": "icon-write",
					"options": {
						"type": "text",
						"width": "100%",
						"defaultValue": "",
						"placeholder": "请输入",
						"clearable": false,
						"maxLength": null,
						"addonBefore": "",
						"addonAfter": "",
						"showLabel": true,
						"hidden": false,
						"disabled": false
					},
					"model": "input_1708566990593",
					"key": "input_1708566990593",
					"help": "",
					"rules": [
						{
							"required": true,
							"message": "必填项"
						}
					]
				}
			],
			"options": {
				"scrollY": 0,
				"disabled": false,
				"hidden": false,
				"showLabel": false,
				"hideSequence": false,
				"width": "100%"
			},
			"model": "batch_1708566980234",
			"key": "batch_1708566980234",
			"help": ""
		}
	],
	"config": {
		"layout": "horizontal",
		"labelCol": {
			"xs": 4,
			"sm": 4,
			"md": 4,
			"lg": 4,
			"xl": 4,
			"xxl": 4
		},
		"labelWidth": 100,
		"labelLayout": "flex",
		"wrapperCol": {
			"xs": 18,
			"sm": 18,
			"md": 18,
			"lg": 18,
			"xl": 18,
			"xxl": 18
		},
		"hideRequiredMark": false,
		"customStyle": ""
	}
}

**Comment by Kchengz** [comment]
我使用在线demo和你这边提供的json，无法复现该问题
[http://cdn.kcz66.com/k-form-design.html](http://cdn.kcz66.com/k-form-design.html)
![1708609710414](https://github.com/Kchengz/k-form-design/assets/37854947/90492b3a-eef3-420e-9c1a-7a31f5979af9)
![1708609835666](https://github.com/Kchengz/k-form-design/assets/37854947/32ca3bf1-ccac-4baa-85d4-fd87db6dc592)
