### ISSUE TITLE
hidden为true时，表单项依然占位置

### ISSUE THREAD

**Issue by chengcan0717** [Kchengz/k-form-design#19]
https://codesandbox.io/s/stoic-murdock-flqbs?file=/src/App.vue
当options设置为true时，表单的项依然占位置（输入框5），望大佬修复一下。

**Comment by Kchengz** [comment]
修复啥，你使用了栅格布局，span = 8呢, 使用栅格布局的问题

**Comment by Kchengz** [comment]
虽然控件已经隐藏了，但是栅格布局设置了span=8，依然会占位置的
