### ISSUE TITLE
使用布局组件的时候，表单没有对齐

### ISSUE THREAD

**Issue by langhaoabcd** [Kchengz/k-form-design#22]
![image](https://user-images.githubusercontent.com/39892654/86559333-427d7180-bf8e-11ea-89f0-890d151ba78d.png)
使用了布局组件，预览出来看布局组件和表单组件的左标签没对齐

**Comment by Kchengz** [comment]
布局控件，只有栅格能控制宽度，表单label标签宽度，也是用栅格单位调整的
