### ISSUE TITLE
Button, Editor 等组件的 hidden 属性不起效

### ISSUE THREAD

**Issue by shaoye** [Kchengz/k-form-design#24]
当 hidden = true 时未起效。其他组件都正常， disable属性也都正常

**Comment by shaoye** [comment]
> 当 hidden = true 时未起效。其他组件和disable属性都正常

**Comment by Kchengz** [comment]
因为只在基础输入控件部分添加了判断条件，在按钮及编辑器组件部门没有添加判断，感谢您反馈，后面会修复这个问题
