### ISSUE TITLE
隐藏字段设置了默认值，无法保存

### ISSUE THREAD

**Issue by jerometang** [Kchengz/k-form-design#25]
表单设计了A字段，默认值为1
表单运行提交后的JSON里并没有包含a字段。

**Comment by Kchengz** [comment]
> 表单设计了A字段，默认值为1
> 表单运行提交后的JSON里并没有包含a字段。

不清楚您说的那个控件无法设置默认值

**Comment by Kchengz** [comment]
可能您说的是无法获取隐藏字段数据，隐藏字段实现是用 v-if来实现的，而非v-show，所以组件隐藏时，实际是被移除了的（非真正隐藏），所以无法获取到被移除的字段数据
