### ISSUE TITLE
树形选择器怎么赋值？

### ISSUE THREAD

**Issue by yinzi2012** [Kchengz/k-form-design#31]
树形选择器怎么赋值？从后台得到一个数组 arr，这个值怎么赋给树形选择器？
把arr赋值给动态数据变量名看不到数据。

**Comment by Kchengz** [comment]
可以(查看文档)[http://kcz66.gitee.io/k-form-design/#/zh-cn/components/build?id=%e5%8a%a8%e6%80%81%e6%95%b0%e6%8d%ae%e9%85%8d%e7%bd%ae]
