### ISSUE TITLE
单行输入框和文本框的maxlength配置栏没有展示

### ISSUE THREAD

**Issue by gaoliang** [Kchengz/k-form-design#33]

**Comment by JansonSK** [comment]
好像vue 3.0 不能支持吧

**Comment by Kchengz** [comment]
> 好像vue 3.0 不能支持吧

不支持

**Comment by Kchengz** [comment]
[https://github.com/Kchengz/k-form-design/commit/5cf7a04a6b9f33b3e658c0c4e9b6ad16772d9e2a](https://github.com/Kchengz/k-form-design/commit/5cf7a04a6b9f33b3e658c0c4e9b6ad16772d9e2a)
