### ISSUE TITLE
k-form-build 下拉框经常会出现数据不渲染的情况

### ISSUE THREAD

**Issue by heihuahe** [Kchengz/k-form-design#35]
情况：使用k-form-build生成动态表单，在配置的时候下拉框是有2个可选项的，但是在使用的时候它经常不渲染选项，不知道是什么原因。。。
k-form-design版本3.6.1

**Comment by JansonSK** [comment]
你的 vue 3.0 版本的吗

**Comment by Kchengz** [comment]
是否使用了其他ui，与其他ui冲突了
