### ISSUE TITLE
样式表 导入哪个文件啊？谢谢

### ISSUE THREAD

**Issue by shaohaojiecoder** [Kchengz/k-form-design#4]
样式表 导入哪个文件啊？谢谢

**Comment by shaohaojiecoder** [comment]
导入成功了， 不过好像污染了其他组件的样式

**Comment by shaohaojiecoder** [comment]
而且保存按钮建 点击没效果 没有触发 handleSave

**Comment by shaohaojiecoder** [comment]
找到问题了 应该是是@save="selfHandleSave" demo上写的不太清楚

**Comment by Kchengz** [comment]
> 导入成功了， 不过好像污染了其他组件的样式

感谢指出问题，之前没考虑到这个问题

**Comment by Kchengz** [comment]
> 样式表 导入哪个文件啊？谢谢
可以在main.js文件添加
import "k-form-design/lib/k-form-design.css";

**Comment by shaohaojiecoder** [comment]
嗯 是的，找到了呢

**Comment by shaohaojiecoder** [comment]
demo 上写的@handleSave 应该是@save 吧？

**Comment by Kchengz** [comment]
> 而且保存按钮建 点击没效果 没有触发 handleSave



> 找到问题了 应该是是@save="selfHandleSave" demo上写的不太清楚
是的，忘记更新文档了，晚上会更新样式污染问题和文档

**Comment by Kchengz** [comment]
修复了样式污染问题[136bd13](https://github.com/Kchengz/k-form-design/commit/692a3057e038e5469879c78acca93ad8d00373ae#diff-0b65f08df5f5789396cda1ed31d48bf6L16)
