### ISSUE TITLE
请教个关于递归组件问题

### ISSUE THREAD

**Issue by whateveryoudo** [Kchengz/k-form-design#41]
看了下源码，不太明白handleColAdd  为什么需要  深拷贝 一份listString

**Comment by Kchengz** [comment]
> 看了下源码，不太明白handleColAdd 为什么需要 深拷贝 一份listString
如果不深拷贝数据，会出现子节点引用自身，自身又包括子节点，这会导致数据出现循环引用，在渲染时导致内存溢出
