### ISSUE TITLE
表格的合并有问题

### ISSUE THREAD

**Issue by wenkm** [Kchengz/k-form-design#43]
先合并单元格，然后新增单元格就会出问题。如图：

https://user-images.githubusercontent.com/3335540/106106418-76b1bd00-6180-11eb-9044-124af584f6be.mp4

![Large GIF (1008x770)](https://user-images.githubusercontent.com/3335540/106106465-88936000-6180-11eb-82a0-aa8b2598153c.gif)

**Comment by Kchengz** [comment]
这部分代码确实存在bug，目前只实现了比较简单的合并处理，因为个人能力有限，做的不是很好，后面会考虑完善一下这部分代码

**Comment by Linzsong** [comment]
我也发现了这个问题，这个是因为“增加一行”的时候，新增行的行号不对所导致的，需要修改“新增一行”的函数handleAddRow()最后一行改为
```js
     // 记录行该行所占的格数，因为这里不可能永远是1，随着合并，占的行数会改变
      let differRow = this.rightMenuSelectValue.trs[this.trIndex].tds[this.tdIndex].rowspan
      this.rightMenuSelectValue.trs.splice(this.trIndex + differRow, 0, rowJson);
```
这样虽然新增行变正常了，但向下合并依然是存在这个bug，如三行中进行两次向下合并就会发现问题。
然后我是给每一个单元格进行唯一标识如(0,0)(0,1)(1,0)(1,1)，合并时进行唯一标识的合并，这样不仅可以精确的合并（行合并的难处就在于无法找打下一行在哪里，是第几个），还可以用唯一标识进行拆分单元格和删除单元格。

**Comment by Kchengz** [comment]
已修复bug[ceb8262ed106a4a4faca4a610dd43446a036b15c](https://github.com/Kchengz/k-form-design/commit/ceb8262ed106a4a4faca4a610dd43446a036b15c)
