### ISSUE TITLE
有对原有控件进行统一添加属性的吗

### ISSUE THREAD

**Issue by 233cy** [Kchengz/k-form-design#44]
我目前有一个需求是给所有控件添加一个属性，类似标签属性。
如文字描述不清楚，请放大图片看。
如图
![强强强强](https://user-images.githubusercontent.com/29916783/106573153-3e412300-6574-11eb-8661-9ffa00a9083c.png)

**Comment by 233cy** [comment]
@callcter @gaoliang @Kchengz @MeteorOC

**Comment by gaoliang** [comment]
这个需要源码集成定制了，可以看下
`k-form-design/packages/KFormDesign/module/formItemProperties.vue`
和 `k-form-design/packages/KFormDesign/config/formItemsConfig.js`

另外，添加了属性，还要在组件里使用这个属性，否则加了没意义

**Comment by 233cy** [comment]
@gaoliang 你好为什么我NPM安装的插件目录里，没有packages目录呢。
![image](https://user-images.githubusercontent.com/29916783/106832903-82940680-66cd-11eb-97a9-b456b867d966.png)

**Comment by 233cy** [comment]
@gaoliang @233cy @callcter @Kchengz @MeteorOC 
大佬，我把源码下下来了，然后自己做了一定的修改，怎么打包成插件呢。我应该怎么放到我的项目中运行呢。我看npm run命令只有打包LIB目录

**Comment by MeteorOC** [comment]
打包成插件可以参考package.json给出的命令，我记得应该是npm mini 或者 yarn mini (看自己使用的包管理工具) 
![image](https://user-images.githubusercontent.com/38990160/107052593-d35c4a00-6808-11eb-95e6-a0b80031089d.png)
关于如何放到自己的项目中运行，一般来说有三种方法：
1. 上传至npm (自己百度)
2. 上传至公司私有npm （比如说搭建artifactory、verdaccio）
3. 直接将打包后的产物放入项目中的某个地方，直接引用即可，这是最简单暴力的。

**Comment by Kchengz** [comment]
> @gaoliang @233cy @callcter @Kchengz @MeteorOC
> 大佬，我把源码下下来了，然后自己做了一定的修改，怎么打包成插件呢。我应该怎么放到我的项目中运行呢。我看npm run命令只有打包LIB目录

npm run lib 或者 yarn lib打包即可，添加属性需要对源码进行修改才行
