### ISSUE TITLE
select 勾选搜索之后 搜索的是value 而不是label

### ISSUE THREAD

**Issue by chlorishi** [Kchengz/k-form-design#46]

**Comment by chlorishi** [comment]
@callcter @gaoliang @Kchengz @MeteorOC  大佬们能帮我解答一下嘛

**Comment by Aurora-shu** [comment]
别想了，自定义组件注册送给你，或者下源码，自己更新然后新建一个npm源

**Comment by Kchengz** [comment]
最新源码已经支持搜索value，[查看更新代码](https://github.com/Kchengz/k-form-design/pull/40/commits/654cd59b199aa16f940008c43241bf785fef263d)，感谢[meteor](https://github.com/MeteorOC)提的PR
