### ISSUE TITLE
关于k-form-design 4.x开发讨论及建议

### ISSUE THREAD

**Issue by Kchengz** [Kchengz/k-form-design#53]
关于k-form-design 4.x开发讨论及建议
 
 1. 使用vue3 Typescript进行项目重构
 2. 增加表单关联功能
 3. 增加编辑撤回功能
 4. ......

如果您有其他建议，请留言

**Comment by afish177** [comment]
希望大佬
新增那种popup 弹出选择数据列表 --带出数据(支持多选）
货币组件
级联父子表格单组件(联动)

**Comment by Kchengz** [comment]
> 新增那种popup 弹出选择数据列表 --带出数据(支持多选）
> 货币组件

最好带一下示例地址或者图片，只有名称的话，我可能不太清楚具体是什么样的组件，动态数据后面会考虑增加通过api来获取数据

**Comment by suyana** [comment]
建议废除栅格控件，在每个控件添加span属性达到栅格控件等一行2列的效果。移动端可以强制设置为24，避免控件在移动端太小。

**Comment by zhugeliangliang** [comment]
建议增加表单内控件关联，可以在控件属性控制对单个控件进行绑定，根据其他控件的值的变化进行计算和数据回填

**Comment by zhugeliangliang** [comment]
建议增加一个控件对其他个控件进行隐藏显示操作，例如：控件A为单选框，控件B为输入框，点击控件A，我已入职，控件B显示输入公司名称，点击没有公司，控件B隐藏

**Comment by zhugeliangliang** [comment]
建议增加控件绑定外部接口，并可对表单控件和外部控件进行对应绑定，当表单加载时对接口进行调用，对绑定的控件进行对应接口数据回显

**Comment by afish177** [comment]
> > 新增那种popup 弹出选择数据列表 --带出数据(支持多选）
> > 货币组件
> 
> 最好带一下示例地址或者图片，只有名称的话，我可能不太清楚具体是什么样的组件，动态数据后面会考虑增加通过api来获取数据
popup （支持列表 树形)
![image](https://user-images.githubusercontent.com/32056262/116336593-6b1b7400-a80b-11eb-949a-f7e98d1d6b89.png)
![image](https://user-images.githubusercontent.com/32056262/116336649-81c1cb00-a80b-11eb-9cde-e8a8f07daf1b.png)
![image](https://user-images.githubusercontent.com/32056262/116336894-e7ae5280-a80b-11eb-9bdf-be7a64d93d85.png)

穿梭组件
![image](https://user-images.githubusercontent.com/32056262/116336826-cbaab100-a80b-11eb-8338-3715284041a4.png)
级联面板
![image](https://user-images.githubusercontent.com/32056262/116336952-fac12280-a80b-11eb-9dce-e3236a39cff6.png)
货币组件
![image](https://user-images.githubusercontent.com/32056262/116337578-ecbfd180-a80c-11eb-8614-0431b79d683b.png)

**Comment by zhugeliangliang** [comment]
建议把控件标签描述和控件进行分离，可以对描述进行左对齐，美化显示效果

**Comment by zhugeliangliang** [comment]
建议增加省市县联动组件

**Comment by lzh-boy** [comment]
建议下拉框、树控件等，数据源可以配置API地址及key、value 属性

**Comment by Kchengz** [comment]
> 建议增加省市县联动组件

这种需要数据服务支持的组件，是不会提供的，会提供自定义组件扩展api

**Comment by xys1989** [comment]
可以增加移动端的支持吗

**Comment by qq1059020841** [comment]
SSR 服务端渲染

**Comment by ZhDavid** [comment]
是否可以增加表格布局针对每个单元格宽度和高度进行设置，并优化单元格的合并与拆分功能

**Comment by zhaoqihao** [comment]
增加表单管理功能

**Comment by Endermanpoi** [comment]
动态表格自定义列宽，动态表格支持自定义组件

**Comment by smuki** [comment]
什么时候开始这个 4.0版本的开发?

**Comment by SuperGodFrey** [comment]
希望在4.x中能有查看页面，虽说有disabled的属性可控制表单禁用状态，但是如果能渲染出一个查看界面的话，用户体验更好。动态表格是否可增加自定义width属性。预览模态框增加全屏属性。
![image](https://user-images.githubusercontent.com/17585347/136720974-ef5ea826-30be-410d-8ada-cb6548acf266.png)

**Comment by DHZHY** [comment]
希望可以有个基于k-form-design自定义组件的文档。
可以自己添加antdvue组件库组件，实现里面的API。

**Comment by chenyangchi** [comment]
1.控件级别的样式设置，比如表格的样式
2.label可去掉（现在为空会保留冒号），冒号可选择是否需要， 也是组件中的label样式可设置，比如宽度，现在默认是100 px，只能完整显示6个汉字，想变宽就要全局调整，很不方便
3.增加穿梭框组件

**Comment by Kchengz** [comment]
抱歉抱歉，鸽了一年多了，目前新的版本再开发中了
目前统计很多需求都是需要各种组件，但是内置一堆组件可能并不是一个好的选择
在新的版本中，主要考虑扩展性，可以更方便扩展自定义的组件
同时也希望能够组建一个组件共享平台，大家可以共享自己的组件（通过安装依赖或者源码的方式使用别人组件）

**Comment by wsxe9988** [comment]
适配ant design vue 最新的3.x版本

**Comment by markr512** [comment]
现在这个进度,感觉vue3版本难产了

**Comment by liutian0117** [comment]
适配ant design vue 最新的3.x版本

**Comment by Erimons-chan** [comment]
目前v3有发布的日期吗

**Comment by Kchengz** [comment]
vue3版本 k-form-design 改为 epic-designer
可以关注 [epic-designer](https://github.com/Kchengz/epic-designer) 仓库

**Comment by wen18732367572** [comment]
![Snipaste_2023-12-04_11-07-43](https://github.com/Kchengz/k-form-design/assets/74092945/ff55e0eb-a52d-45a8-b1f1-5f25cee7a4b3)
控件属性设置支持自定义，比如插槽的形式

**Comment by wen18732367572** [comment]
![Snipaste_2023-12-04_11-07-43](https://github.com/Kchengz/k-form-design/assets/74092945/9080af95-fcc9-4188-92df-531d024321bd)
