### ISSUE TITLE
求助帖

### ISSUE THREAD

**Issue by shaohaojiecoder** [Kchengz/k-form-design#7]
楼主，请教个问题：
    有没有办法把模板语法写成的控件vue文件存入数据库中，然后根据拖拽回来 在前端完成渲染和 展示
谢谢

**Comment by Kchengz** [comment]
> 楼主，请教个问题：
> 有没有办法把模板语法写成的控件vue文件存入数据库中，然后根据拖拽回来 在前端完成渲染和 展示
> 谢谢
我不太清楚，你需要的是什么，是需要将设计好的表单保存到数据库，然后可以在表单设计器界面导入数据库的数据吗，然后可以继续修改编辑表单？

**Comment by Kchengz** [comment]
> 楼主，请教个问题：
> 有没有办法把模板语法写成的控件vue文件存入数据库中，然后根据拖拽回来 在前端完成渲染和 展示
> 谢谢

我不太清楚，你需要的是什么，是需要将设计好的表单保存到数据库，然后可以在表单设计器界面导入数据库的数据吗，然后可以继续修改编辑表单？

**Comment by shaohaojiecoder** [comment]
是的，可以加下我微信吗？shjamwzj

**Comment by Kchengz** [comment]
> 是的，可以加下我微信吗？shjamwzj

可以
