### ISSUE TITLE
不支持密码框

### ISSUE THREAD

**Issue by Kerbores** [Kchengz/k-form-design#8]
单行文本框不支持密码框

**Comment by Kchengz** [comment]
> 单行文本框不支持密码框

对哦，后面会在单行文本里面提供属性type，可以设置type为password

**Comment by Kerbores** [comment]
同时提几点其他的建议:

1. 通过v:bind的方式对组件原始属性进行绑定,设计器提供一个字段来指定此属性
2. 必填字段的validator中message默认使用字段的placeholder会更好一些
3. 表格布局可以设置为动态添加列,然后数据默认绑定到一个Array上

**Comment by Kchengz** [comment]
> 同时提几点其他的建议:
> 
> 1. 通过v:bind的方式对组件原始属性进行绑定,设计器提供一个字段来指定此属性
> 2. 必填字段的validator中message默认使用字段的placeholder会更好一些
> 3. 表格布局可以设置为动态添加列,然后数据默认绑定到一个Array上

第一点，我不太明白
第二点，使用message是因为表单验证使用的ant-design  Form组件自带校验规则，默认使用的是message为校验文案，[查看a-form 校验规则](https://www.antdv.com/components/form-cn/#%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99)
第三点，是想要添加行列吗，可以右键表格添加行列，合并单元格，当然这里的操作存在一些bug，不是很完善

**Comment by Kerbores** [comment]
第一点,比如单行文本要支持密码框,其实就是a-input组件设置了password属性,但是各个表单组件的属性很多,如果每一个都去根据组件把全部属性支持了的话是个很麻烦的事情,就按照现在的方式写一下常见的属性配置即可,如果用户需要更深入的定制,在设计器的每个组件都设置一个属性框,填入的内容就是需要自定义的属性的json描述,然后通过v:bind方式绑定到antd的原始组件上来实现原始组件的属性绑定,这样就不用每个组件都去声明一遍全部的属性,可大大的提高使用者的coding效率,同时又能兼顾深入定制的需求

**Comment by Kerbores** [comment]
第二点的意思是既然我们都已经写了placeholder信息了,为什么不把这个信息直接带到验证规则必填的message中,这样提示起来更加语义化,不然生成json之后还得一个一个去修改必填验证的massage,或者是提供一个开关来设定是否使用placeholder信息作为必填验证的massage

**Comment by Kerbores** [comment]
第三点的意思是在用户填写表单的过程中需要填写一个单条的数据,然后这个数据有一个属性是一个列表,列表的长度是非固定的,这个时候用户写表单的时候点一下添加就增加一行,然后把列表的数据绑定到表单数据对象的一个array上,不知是否于目前的表格布局设计初衷有冲突.

**Comment by Kchengz** [comment]
> 第二点的意思是既然我们都已经写了placeholder信息了,为什么不把这个信息直接带到验证规则必填的message中,这样提示起来更加语义化,不然生成json之后还得一个一个去修改必填验证的massage,或者是提供一个开关来设定是否使用placeholder信息作为必填验证的massage

这个可以考虑用个开关来控制

**Comment by Kchengz** [comment]
> 属性框,填入的内容就是需要自定义的属性的json描述,然后通过v:bind方式绑定到antd的原始组件上来实现原始组件

暂不知道有没有属性支持直接通过json绑定api，如果只用v-bind似乎得把所有api写v-bind，我只是挑了一些常用的属性给用户配置，如果用户需要自定义比较多，可以插入[自定义表单控件](http://www.kcz66.com/k-form-design/#/zh-cn/field/custom)，[自定义控件规制](https://ant.design/components/form-cn/#components-form-demo-customized-form-controls)
> 自定义或第三方的表单控件，也可以与 Form 组件一起使用。只要该组件遵循以下的约定：
- 提供受控属性 value 或其它与 valuePropName 的值同名的属性。
- 提供 onChange 事件或 trigger 的值同名的事件。
- 支持 ref：
  - React@16.3.0 之前只有 Class 组件支持。
  - React@16.3.0 及之后可以通过 forwardRef 添加 ref 支持

**Comment by Kchengz** [comment]
> 第三点的意思是在用户填写表单的过程中需要填写一个单条的数据,然后这个数据有一个属性是一个列表,列表的长度是非固定的,这个时候用户写表单的时候点一下添加就增加一行,然后把列表的数据绑定到表单数据对象的一个array上,不知是否于目前的表格布局设计初衷有冲突.

这个应该是一个子表单，后面考虑添加这个组件，与表格布局不冲突，表格布局仅用于页面布局排版，现版本用户可通过自定义控件添加
